name: Maven Create Release

"on":
  workflow_dispatch:
    inputs:
      repo-name:
        type: choice
        required: true
        default: de-nile-data-model
        options:
        - de-nile-enrichment
        - de-nile-data-model
        - de-nile-data-model
        - de-nile-data-model
      branch-name:
        required: true
        default: master
        description: branch name of the repo you want to release


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v2