# Example workflow
name: Format

on: [push]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
          version: 1.13.0
          files: src/main/java/model/**/*.java

