# Example workflow
name: Format

on: [pull_request]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
        with:
          version: 1.13.0
          files: src/main/java/com.pluto.model/**/*.java

